Repository open-quantum-safe/liboqs, pull requests merged in 2018-09, with the labels that each got.

#348 Add KAT checks
  .gitignore
  .travis.yml
  .travis/kat-check.sh
  Makefile.am
  VisualStudio/oqs/oqs.vcxproj
  VisualStudio/oqs/oqs.vcxproj.filters
  scripts/check_kats.sh
  src/common/Makefile.am
  src/common/rand.c
  src/common/rand.h
  src/common/rand_nist.c
  src/kem/bike/BIKE1-L1-Additional.kat
  src/kem/bike/BIKE1-L1.Additional.const.kat
  src/kem/bike/BIKE1-L1.Additional.kat
  src/kem/bike/BIKE1-L1.kat
  src/kem/bike/BIKE1-L3-Additional.kat
  src/kem/bike/BIKE1-L3.Additional.const.kat
  src/kem/bike/BIKE1-L3.Additional.kat
  src/kem/bike/BIKE1-L3.kat
  src/kem/bike/BIKE1-L5-Additional.kat
  src/kem/bike/BIKE1-L5.Additional.const.kat
  src/kem/bike/BIKE1-L5.Additional.kat
  src/kem/bike/BIKE1-L5.kat
  src/kem/bike/BIKE2-L1-Additional.kat
  src/kem/bike/BIKE2-L1.Additional.const.kat
  src/kem/bike/BIKE2-L1.Additional.kat
  src/kem/bike/BIKE2-L1.kat
  src/kem/bike/BIKE2-L3-Additional.kat
  src/kem/bike/BIKE2-L3.Additional.const.kat
  src/kem/bike/BIKE2-L3.Additional.kat
  src/kem/bike/BIKE2-L3.kat
  src/kem/bike/BIKE2-L5-Additional.kat
  src/kem/bike/BIKE2-L5.Additional.const.kat
  src/kem/bike/BIKE2-L5.Additional.kat
  src/kem/bike/BIKE2-L5.kat
  src/kem/bike/BIKE3-L1-Additional.kat
  src/kem/bike/BIKE3-L1.Additional.const.kat
  src/kem/bike/BIKE3-L1.Additional.kat
  src/kem/bike/BIKE3-L1.kat
  src/kem/bike/BIKE3-L3-Additional.kat
  src/kem/bike/BIKE3-L3.Additional.const.kat
  src/kem/bike/BIKE3-L3.Additional.kat
  src/kem/bike/BIKE3-L3.kat
  src/kem/bike/BIKE3-L5-Additional.kat
  src/kem/bike/BIKE3-L5.Additional.const.kat
  src/kem/bike/BIKE3-L5.Additional.kat
  src/kem/bike/BIKE3-L5.kat
  src/kem/frodokem/FrodoKEM-640-AES.kat
  src/kem/frodokem/FrodoKEM-640-cSHAKE.kat
  src/kem/frodokem/FrodoKEM-976-AES.kat
  src/kem/frodokem/FrodoKEM-976-cSHAKE.kat
  src/kem/sike/Sike-p503.kat
  src/kem/sike/Sike-p751.kat
  tests/Makefile.am
  tests/kat_kem.c
Labels: master, not ready for merge

#361 Add AES 256 and refactor AES test vectors
  src/crypto/aes/aes.c
  src/crypto/aes/aes.h
  src/crypto/aes/aes_c.c
  src/crypto/aes/aes_local.h
  tests/test_aes.c
Labels: enhancement, master

#364 Don't symbolically link liboqs.a in make links
  Makefile.am
Labels: bug, master

#365 Titanium: fix NIST level in data sheet
  docs/algorithms/kem_titanium.md
Labels: nist-branch

#373 Titanium: tweak data sheet with author's updates.
  docs/algorithms/kem_titanium.md
Labels: documentation, nist-branch

#342 Update timing header
  src/common/ds_benchmark.h
Labels: enhancement, nist-branch

#378 Fix some typos
  .gitignore
  README.md
Labels: documentation, master

#376 Added troubleshooting for contributing.md
  CONTRIBUTING.md
Labels: documentation, nist-branch

#381 Too early to make
  README.md
Labels: documentation, master

#385 Remove residual KEX sidh_msr (#369).
  .gitignore
  .travis.yml
  .travis/all-tests.sh
  docs/.Doxyfile
Labels: master, not ready for merge, refactor

#387 Remove superfluous extern keywords from KEMs.
  src/kem/BIG_QUAKE/kem_BIGQUAKE.h
  src/kem/bike/kem_bike.h
  src/kem/crystals-kyber/kem_kyber.h
  src/kem/frodokem/kem_frodokem.h
  src/kem/ledakem/kem_ledakem.h
  src/kem/lima/kem_lima.h
  src/kem/newhopenist/kem_newhopenist.h
  src/kem/saber/kem_saber.h
Labels: nist-branch, refactor

#384 Remove kex_code_mcbits (issue 371).
  .travis.yml
  .travis/all-tests.sh
  Makefile.am
  README.md
  VisualStudio/oqs/oqs.vcxproj
  config/features.m4
  configure.ac
  docs/.Doxyfile
  src/kex/kex.c
  src/kex/kex.h
  src/kex_code_mcbits/LICENSE.txt
  src/kex_code_mcbits/Makefile.am
  src/kex_code_mcbits/external/api.h
  src/kex_code_mcbits/external/benes.c
  src/kex_code_mcbits/external/bm.c
  src/kex_code_mcbits/external/consts.data
  src/kex_code_mcbits/external/decrypt.c
  src/kex_code_mcbits/external/encrypt.c
  src/kex_code_mcbits/external/fft.c
  src/kex_code_mcbits/external/fft_tr.c
  src/kex_code_mcbits/external/gf.c
  src/kex_code_mcbits/external/implementors
  src/kex_code_mcbits/external/operations.c
  src/kex_code_mcbits/external/params.h
  src/kex_code_mcbits/external/pk_gen.c
  src/kex_code_mcbits/external/points.data
  src/kex_code_mcbits/external/scalars.data
  src/kex_code_mcbits/external/scalars_2x.data
  src/kex_code_mcbits/external/sk_gen.c
  src/kex_code_mcbits/external/transpose.c
  src/kex_code_mcbits/external/util.c
  src/kex_code_mcbits/external/vec.c
  src/kex_code_mcbits/kex_code_mcbits.c
  src/kex_code_mcbits/kex_code_mcbits.h
  src/kex_code_mcbits/mcbits.h
  tests/test_kex.c
Labels: master, not ready for merge, refactor

#393 Sig API fixes
  src/sig/example_sig.c
  src/sig/sig.c
Labels: not ready for merge

#394 Remove superfluous externs
  src/sig/crystals-dilithium/sig_dilithium.h
  src/sig/picnic/sig_picnic.h
  src/sig/qtesla/sig_qtesla.h
Labels: nist-branch, refactor
