Repository open-quantum-safe/liboqs, pull requests merged in 2018-10, with the labels that each got.

#363 Shared library support added
  .travis/all-tests.sh
  Makefile.am
  config/detect_host_and_cpu.m4
  config/features.m4
  configure.ac
  src/common/common.c
  src/common/rand_nist.c
  src/kem/bike/Makefile.am
  src/kem/frodokem/kem.c
  src/kem/frodokem/kem_frodokem.h
  tests/Makefile.am
Labels: enhancement, master

#397 Sync common files on master with nist-branch
  .travis.yml
  .travis/algorithm-datasheets-check.sh
  .travis/free-check.sh
  .travis/style-check.sh
  docs/algorithms/sig_qtesla.md
  scripts/check_kats.sh
  src/common/common.c
  src/common/common.h
  src/common/rand.c
  src/common/rand.h
  src/common/rand_nist.c
  src/kem/kem.c
  src/kem/kem.h
  src/sig/sig.c
  src/sig/sig.h
  tests/Makefile.am
  tests/ds_benchmark.h
  tests/example_kem.c
  tests/minimal_kex_oqs.c
  tests/test_kem.c
  tests/test_kex.c
  tests/test_rand.c
  tests/test_sig.c
Labels: master, refactor

#382 Master add kem newhopenist
  Makefile.am
  VisualStudio/oqs/oqs.vcxproj
  VisualStudio/oqs/oqs.vcxproj.filters
  VisualStudio/winconfig.h
  config/features.m4
  configure.ac
  docs/algorithms/kem_newhope.md
  src/kem/kem.c
  src/kem/kem.h
  src/kem/newhope/Makefile.am
  src/kem/newhope/NEWHOPE-1024CCA.Optimized.kat
  src/kem/newhope/NEWHOPE-512CCA.Optimized.kat
  src/kem/newhope/functions_renaming.h
  src/kem/newhope/kem_newhope.c
  src/kem/newhope/kem_newhope.h
  src/kem/newhope/optimized/api.h
  src/kem/newhope/optimized/cpapke.c
  src/kem/newhope/optimized/cpapke.h
  src/kem/newhope/optimized/fips202.h
  src/kem/newhope/optimized/kem.c
  src/kem/newhope/optimized/ntt.c
  src/kem/newhope/optimized/ntt.h
  src/kem/newhope/optimized/params.h
  src/kem/newhope/optimized/poly.c
  src/kem/newhope/optimized/poly.h
  src/kem/newhope/optimized/precomp.c
  src/kem/newhope/optimized/reduce.c
  src/kem/newhope/optimized/reduce.h
  src/kem/newhope/optimized/verify.c
  src/kem/newhope/optimized/verify.h
  src/kem/newhope/win_newhope1024cca.c
  src/kem/newhope/win_newhope512cca.c
Labels: master

#403 Remove old OQS_RAND object and API
  .gitignore
  Makefile.am
  README.md
  VisualStudio/oqs/dll.def
  VisualStudio/oqs/oqs.vcxproj
  VisualStudio/oqs/oqs.vcxproj.filters
  VisualStudio/test_rand/test_rand.vcxproj
  VisualStudio/test_rand/test_rand.vcxproj.filters
  configure.ac
  docs/.Doxyfile
  src/common/common.c
  src/common/common.h
  src/common/rand.c
  src/common/rand.h
  src/crypto/rand_urandom_aesctr/Makefile.am
  src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.c
  src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.h
  src/crypto/rand_urandom_chacha20/Makefile.am
  src/crypto/rand_urandom_chacha20/external/LICENSE.txt
  src/crypto/rand_urandom_chacha20/external/chacha20.c
  src/crypto/rand_urandom_chacha20/external/ecrypt-config.h
  src/crypto/rand_urandom_chacha20/external/ecrypt-portable.h
  src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.c
  src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.h
  src/sig/qtesla/external/qTESLA_I.c
  src/sig/qtesla/external/qTESLA_I.h
  src/sig/qtesla/external/qTESLA_III_size.c
  src/sig/qtesla/external/qTESLA_III_size.h
  src/sig/qtesla/external/qTESLA_III_speed.c
  src/sig/qtesla/external/qTESLA_III_speed.h
  src/sig/qtesla/sig_qtesla.c
  src/sig/qtesla/sig_qtesla.h
  tests/Makefile.am
  tests/kat_kem.c
  tests/minimal_kex_oqs.c
  tests/test_aes.c
  tests/test_kem.c
  tests/test_kex.c
  tests/test_rand.c
Labels: master, refactor

#409 Remove execute permissions from source files
  src/kem/newhope/optimized/fips202.h
  src/kem/newhope/optimized/reduce.h
  src/kem/newhope/optimized/verify.h
Labels: master

#414 Clarify public versus internal API and documentation
  Makefile.am
  README.md
  docs/.Doxyfile
  src/common/common.h
Labels: documentation, master, refactor

#412 Rename NewHope to NewHopeNIST to be consistent with nist-branch
  Makefile.am
  VisualStudio/oqs/oqs.vcxproj
  VisualStudio/oqs/oqs.vcxproj.filters
  VisualStudio/winconfig.h
  config/features.m4
  configure.ac
  docs/algorithms/kem_newhope.md
  docs/algorithms/kem_newhopenist.md
  src/kem/kem.c
  src/kem/kem.h
  src/kem/newhope/Makefile.am
  src/kem/newhope/kem_newhope.c
  src/kem/newhope/kem_newhope.h
  src/kem/newhopenist/Makefile.am
  src/kem/newhopenist/NEWHOPE-1024CCA.Optimized.kat
  src/kem/newhopenist/NEWHOPE-512CCA.Optimized.kat
  src/kem/newhopenist/functions_renaming.h
  src/kem/newhopenist/kem_newhopenist.c
  src/kem/newhopenist/kem_newhopenist.h
  src/kem/newhopenist/optimized/api.h
  src/kem/newhopenist/optimized/cpapke.c
  src/kem/newhopenist/optimized/cpapke.h
  src/kem/newhopenist/optimized/fips202.h
  src/kem/newhopenist/optimized/kem.c
  src/kem/newhopenist/optimized/ntt.c
  src/kem/newhopenist/optimized/ntt.h
  src/kem/newhopenist/optimized/params.h
  src/kem/newhopenist/optimized/poly.c
  src/kem/newhopenist/optimized/poly.h
  src/kem/newhopenist/optimized/precomp.c
  src/kem/newhopenist/optimized/reduce.c
  src/kem/newhopenist/optimized/reduce.h
  src/kem/newhopenist/optimized/verify.c
  src/kem/newhopenist/optimized/verify.h
  src/kem/newhopenist/win_newhope1024cca.c
  src/kem/newhopenist/win_newhope512cca.c
Labels: master, refactor

#398 Sync common files on nist with master
  .travis/algorithm-datasheets-check.sh
  .travis/all-tests.sh
  .travis/defs.sh
  .travis/free-check.sh
  .travis/install-clang-format-linux.sh
  .travis/kat-check.sh
  .travis/style-check.sh
  scripts/check_kats.sh
  src/common/common.c
  src/common/common.h
  src/common/rand.c
  src/common/rand.h
  src/common/rand_nist.c
  src/kem/example_kem.c
  src/kem/kat_kem.c
  src/kem/kem.c
  src/kem/kem.h
  src/oqs.h
  src/sig/example_sig.c
  src/sig/sig.c
  src/sig/sig.h
  src/sig/test_sig.c
Labels: nist-branch, refactor

#411 Set version in configure, library, and algorithms
  README.md
  RELEASE.md
  configure.ac
  docs/algorithms/kem_bike.md
  docs/algorithms/kem_frodokem.md
  docs/algorithms/kem_newhopenist.md
  docs/algorithms/kem_sidh.md
  docs/algorithms/kem_sike.md
  docs/algorithms/sig_picnic.md
  docs/algorithms/sig_qtesla.md
  src/kem/bike/kem_bike.c
  src/kem/frodokem/kem_frodokem.c
  src/kem/kem.h
  src/kem/newhopenist/kem_newhopenist.c
  src/kem/sike/kem_sike.c
  src/sig/picnic/sig_picnic.c
  src/sig/qtesla/sig_qtesla.c
  src/sig/sig.h
Labels: enhancement, master, not ready for merge

#418 Sync master with nist-branch, including sorting algorithms
  src/common/rand.c
  src/kem/kem.c
  src/kem/kem.h
  src/sig/sig.c
  src/sig/sig.h
  tests/kat_kem.c
  tests/test_kem.c
Labels: master, refactor

#422 Add algorithm version strings and details to NIST branch
  Makefile
  docs/algorithms/kem_BIG_QUAKE.md
  docs/algorithms/kem_frodokem.md
  docs/algorithms/kem_kyber.md
  docs/algorithms/kem_ledakem.md
  docs/algorithms/kem_lima.md
  docs/algorithms/sig_picnic.md
  docs/algorithms/sig_qtesla.md
  src/kem/BIG_QUAKE/kem_BIGQUAKE.c
  src/kem/bike/kem_bike.c
  src/kem/crystals-kyber/kem_kyber.c
  src/kem/frodokem/kem_frodokem.c
  src/kem/kem.h
  src/kem/ledakem/kem_ledakem.c
  src/kem/lima/kem_lima.c
  src/kem/newhopenist/kem_newhopenist.c
  src/kem/saber/kem_saber.c
  src/kem/sike/kem_sike.c
  src/kem/titanium/kem_titanium.c
  src/sig/crystals-dilithium/sig_dilithium.c
  src/sig/picnic/sig_picnic.c
  src/sig/qtesla/sig_qtesla.c
  src/sig/sig.h
Labels: enhancement, nist-branch

#417 Sync nist-branch with master and sort algorithms alphabetically
  .travis/algorithm-datasheets-check.sh
  docs/.Doxyfile
  src/common/common.c
  src/common/common.h
  src/common/rand.c
  src/common/rand.h
  src/kem/kat_kem.c
  src/kem/kem.c
  src/kem/kem.h
  src/kem/test_kem.c
  src/sig/sig.c
  src/sig/sig.h
Labels: nist-branch, refactor

#428 Remove binary files from git index
  src/kem/ledakem/upstream/Reference_Implementation/KEM/library/a.out
  src/sig/qtesla/upstream/Reference_implementation/qTesla_I/PQCgenKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_I/PQCtestKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_I/test_qtesla
  src/sig/qtesla/upstream/Reference_implementation/qTesla_III_size/PQCgenKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_III_size/PQCtestKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_III_size/test_qtesla
  src/sig/qtesla/upstream/Reference_implementation/qTesla_III_speed/PQCgenKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_III_speed/PQCtestKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_III_speed/test_qtesla
  src/sig/qtesla/upstream/Reference_implementation/qTesla_p_I/PQCgenKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_p_I/PQCtestKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_p_I/test_qtesla
  src/sig/qtesla/upstream/Reference_implementation/qTesla_p_III/PQCgenKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_p_III/PQCtestKAT_sign
  src/sig/qtesla/upstream/Reference_implementation/qTesla_p_III/test_qtesla
Labels: enhancement, nist-branch

#427 Add version string for Dilithium SIG
  docs/algorithms/kem_newhopenist.md
  docs/algorithms/sig_dilithium.md
  src/kem/newhopenist/NewHope-1024-CCA-KEM.kat
  src/kem/newhopenist/NewHope-512-CCA-KEM.kat
  src/sig/crystals-dilithium/sig_dilithium.c
Labels: documentation, enhancement, nist-branch

#430 Adapting BIKE2 to the new OpenSSL API
  src/kem/bike/ref/openssl_utils.c
  src/kem/bike/x86_64/openssl_utils.c
Labels: master

#431 Adapting BIKE2 to the new OpenSSL API
  src/kem/bike/upstream/additional_implementation/openssl_utils.c
  src/kem/bike/upstream/reference_implementation/openssl_utils.c
Labels: nist-branch

#434 Fix typo in sig name in comment block
  tests/example_sig.c
Labels: documentation, master
