Repository open-quantum-safe/liboqs, pull requests merged in 2018-12, with the labels that each got.

#446 Link to liboqs-utils project in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, nist-branch

#449 Adds functions to count the number of supported KEMs/sigs
  VisualStudio/oqs/dll.def
  src/kem/kem.c
  src/kem/kem.h
  src/sig/sig.c
  src/sig/sig.h
Labels: enhancement

#447 Smallfixes
  src/kem/frodokem/kem.c
  src/kem/newhopenist/optimized/cpapke.c
  src/kem/newhopenist/optimized/fips202.h
  src/kem/newhopenist/optimized/kem.c
  src/kem/newhopenist/optimized/ntt.c
  src/kem/newhopenist/optimized/poly.c
Labels: master, refactor

#448 Kyber
  Makefile.am
  VisualStudio/oqs/oqs.vcxproj
  config/features.m4
  configure.ac
  docs/algorithms/kem_kyber.md
  src/kem/kem.c
  src/kem/kem.h
  src/kem/kyber/Kyber-1024-CCA-KEM.kat
  src/kem/kyber/Kyber-512-CCA-KEM.kat
  src/kem/kyber/Kyber-768-CCA-KEM.kat
  src/kem/kyber/Makefile.am
  src/kem/kyber/functions_renaming.h
  src/kem/kyber/kem_kyber.c
  src/kem/kyber/kem_kyber.h
  src/kem/kyber/ref/api.h
  src/kem/kyber/ref/cbd.c
  src/kem/kyber/ref/cbd.h
  src/kem/kyber/ref/indcpa.c
  src/kem/kyber/ref/indcpa.h
  src/kem/kyber/ref/kem.c
  src/kem/kyber/ref/ntt.c
  src/kem/kyber/ref/ntt.h
  src/kem/kyber/ref/params.h
  src/kem/kyber/ref/poly.c
  src/kem/kyber/ref/poly.h
  src/kem/kyber/ref/polyvec.c
  src/kem/kyber/ref/polyvec.h
  src/kem/kyber/ref/precomp.c
  src/kem/kyber/ref/reduce.c
  src/kem/kyber/ref/reduce.h
  src/kem/kyber/ref/verify.c
  src/kem/kyber/ref/verify.h
  src/kem/kyber/win_kyber1024.c
  src/kem/kyber/win_kyber512.c
  src/kem/kyber/win_kyber768.c
Labels: enhancement, master
