Repository open-quantum-safe/liboqs, pull requests merged in 2018-08, with the labels that each got.

#329 Make doxygen mandatory and fix undocumented functions / add deprecation notices
  .travis.yml
  .travis/all-tests.sh
  docs/.Doxyfile
  src/common/common.h
  src/common/rand.h
  src/crypto/aes/aes.h
  src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.h
  src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.h
  src/kex/kex.h
  src/kex_code_mcbits/kex_code_mcbits.h
  src/kex_ntru/kex_ntru.c
  src/kex_ntru/kex_ntru.h
  src/kex_ntru/ntru_crypto_platform.h
  src/kex_rlwe_newhope/kex_rlwe_newhope.h
  src/kex_sidh_msr/kex_sidh_msr.h
  src/sig/sig.h
Labels: documentation, master

#335 Move tests to a common directory
  .gitignore
  Makefile.am
  configure.ac
  tests/Makefile.am
  tests/ds_benchmark.h
  tests/example_kem.c
  tests/minimal_kex_oqs.c
  tests/minimal_sig_oqs.c
  tests/speed_kem.c
  tests/test_aes.c
  tests/test_kem.c
  tests/test_kex.c
  tests/test_rand.c
  tests/test_sha3.c
  tests/test_sig.c
Labels: master, refactor

#337 Update URL and ZIP file name for Keccak code package
  Makefile
  README.md
  scripts/build-keccak-code-package.sh
Labels: bug, nist-branch

#339 Update README on nist-branch
  README.md
Labels: documentation, nist-branch

#340 Update README
  README.md
Labels: documentation, master

#352 Fixed Visual Studio build after master's API refactoring.
  VisualStudio/liboqs.sln
  VisualStudio/minimal_kex_oqs/minimal_kex_oqs.vcxproj
  VisualStudio/minimal_kex_oqs/minimal_kex_oqs.vcxproj.filters
  VisualStudio/minimal_sig_oqs/minimal_sig_oqs.vcxproj
  VisualStudio/minimal_sig_oqs/minimal_sig_oqs.vcxproj.filters
  VisualStudio/oqs/oqs.vcxproj
  VisualStudio/oqs/oqs.vcxproj.filters
  VisualStudio/test_kex/test_kex.vcxproj
  VisualStudio/test_kex/test_kex.vcxproj.filters
  VisualStudio/test_sig/test_sig.vcxproj
  VisualStudio/test_sig/test_sig.vcxproj.filters
  appveyor.yml
  src/common/common.h
  src/common/rand.c
  tests/minimal_kex_oqs.c
Labels: master

#353 Switch automake to using check for test programs that aren't installed
  Makefile.am
  README.md
  tests/Makefile.am
Labels: bug, master
