Repository open-quantum-safe/liboqs, pull requests merged in 2018-11, with the labels that each got.

#436 Rename OQS' config.h to oqsconfig.h
  .gitignore
  Makefile
  README.md
  src/common/common.h
  src/kem/bike/upstream/additional_implementation/defs.h
  src/kem/example_kem.c
  src/oqs.h
  src/sig/example_sig.c
Labels: nist-branch, refactor

#437 Rename OQS' config.h to oqsconfig.h and separate autoconf variables
  .gitignore
  Makefile.am
  README.md
  config/features.m4
  src/common/common.h
  src/kem/bike/Makefile.am
  src/kem/bike/kem_bike.c
  src/kem/bike/kem_bike.h
  src/kem/bike/ref/types.h
  src/kem/bike/x86_64/defs.h
  src/kem/bike/x86_64/types.h
  src/oqs.h
  tests/example_kem.c
  tests/example_sig.c
Labels: master, refactor

#441 needed to build shared library with other shared libraries like openssl
  Makefile
Labels: nist-branch
